[package]
name = "conways_game_of_life"
version = "0.1.0"
authors = ["Mattis Kaemmerer <mattis.kaemmerer@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion="1.5"
